//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADMIN
    {
        public int AdminId { get; set; }
        [Required(ErrorMessage = "USERNAME IS REQUIRED")]

        [RegularExpression("\\w{5,}", ErrorMessage = "USERNAME SHOULD BE ATLEAST OF LENGTH 5")]

        [Display(Name = "USERNAME")]

        public string UserName { get; set; }
        [DataType(DataType.Password)]

        [Required(ErrorMessage = "PASSWORD IS REQUIRED")]

        [Display(Name = "PASSWORD")]

        [RegularExpression("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$", ErrorMessage = "PASSWORD MUST HAVE ONE CAPS,SPECIAL CHARACTER ,NUMBER AND LENGTH ATLEAST OF 8 ")]

        [StringLength(20, ErrorMessage = "LENGTH SHOULDN'T BE MORE THAN 20")]

        public string Password { get; set; }

        [Required(ErrorMessage = "SECURITY QUESTION IS REQUIRED")]
        public string SecurityQuestion { get; set; }

        [Required(ErrorMessage = "RESPONSE IS REQUIRED")]
        public string Response { get; set; }
    }
}
