//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CIMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class CAR
    {
        public int ID { get; set; }
        [Display(Name = "MODEL")]

        [Required(ErrorMessage = "MODEL IS REQUIRED")]

        [Remote("IsCarModelExist", "CIMS",
         ErrorMessage = "MODEL ALREADY EXISTS")]

        public string Model { get; set; }
        [Required(ErrorMessage = "MANUFACTURER IS REQUIRED")]

        [Display(Name = "MANUFACTURER")]

        public Nullable<int> ManufacturerId { get; set; }
        [Required(ErrorMessage = "TYPE IS REQUIRED")]

        [Display(Name = "TYPE")]
        public Nullable<int> TypeId { get; set; }
        [Required(ErrorMessage = "ENGINE IS REQUIRED")]
        [RegularExpression("\\d+.\\d+L", ErrorMessage = "ENGINE MUST BE IN THIS(4.4L)")]
        [Display(Name = "ENGINE")]
        public string Engine { get; set; }
        [Required(ErrorMessage = "BHP IS REQUIRED")]

        [Display(Name = "BHP")]
        public Nullable<int> BHP { get; set; }
        [Required(ErrorMessage = "TRANSMISSION IS REQUIRED")]

        [Display(Name = "TRANSMISSION")]
        public Nullable<int> TransmissionId { get; set; }

        [Required(ErrorMessage = "MILEAGE IS REQUIRED")]

        [Display(Name = "MILEAGE")]
        public int Mileage { get; set; }
        [Required(ErrorMessage = "SEAT IS REQUIRED")]

        [Display(Name = "NUMBER OF SEATS")]
        public int Seat { get; set; }
        [Required(ErrorMessage = "AIRBAGDETAILS TYPE IS REQUIRED")]

        [Display(Name = "AIRBAG")]
        public string AirBagDetails { get; set; }
        [Required(ErrorMessage = "BOOTSPACE IS REQUIRED")]

        [Display(Name = "BOOTSPACE")]
        public string BootSpace { get; set; }
        [Required(ErrorMessage = "PRICE IS REQUIRED")]

        [Display(Name = "PRICE")]
        public Nullable<decimal> Price { get; set; }

        public virtual Manufacturer Manufacturer { get; set; }
        public virtual CarTransmissionType CarTransmissionType { get; set; }
        public virtual CarType CarType { get; set; }

    }
}
